export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { Bg } from "@/components/background";
import { Console } from "@/components/console";
import { Footer } from "@/components/footer";
import Navbar from "@/components/navbar";
import "@/styles/globals.scss";
import { ThemeProvider } from "next-themes";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider defaultTheme="dark" attribute="class">
          <div id="main">
            <Console />
            <Navbar />
            <Bg />
            <div id="content">
              <div>{children}</div>
              <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
